language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
jobs:
    allow_failures:
        - rust: nightly
    fast_finish: true
sudo: false
script:
    - cargo test --verbose
    - cargo test --verbose --release