[workspace]
members = [
    "client",
    "game",
    "model",
    "protocol",
    "server",
]

[profile.release]
lto = true
debug = 1
incremental = false

[profile.release.package.netholdem-client]
opt-level = "s"