[workspace]
members = [
    "netholdem_client",
    "netholdem_game",
    "netholdem_model",
    "netholdem_protocol",
    "netholdem_server",
]

[profile.release]
lto = true
debug = 1
incremental = false
